// Generated by IcedCoffeeScript 108.0.11

/*
* File: index
* User: Pu
* Date: 11/01/13
* Desc:
 */
var daemonOptions, daemonService, foundation, server, setting, web;

setting = require('./index-setting.json');

foundation = require('clc.foundation');

web = require('clc.foundation.web');

server = new web.Server(setting);

server.start();

daemonOptions = setting.daemon;

if (daemonOptions.mqtt == null) {
  daemonOptions.mqtt = setting.mqtt;
}

daemonService = new foundation.DaemonService(daemonOptions);

daemonService.start();
