// Generated by IcedCoffeeScript 108.0.11

/*
* File: 02_gateway
* User: Dow
* Date: 5/7/2015
* Desc:
 */
var sm;

sm = require('../../app/services/frame/service-manager');

module.exports = function() {
  return sm.startService(['register', 'configuration', 'frame']);
};
