// Generated by IcedCoffeeScript 108.0.11

/*
* File: main
* User: Dow
* Date: 2014/10/24
 */
requirejs(['json!/frame/setting', 'materialize-css', 'angular', './app'], function(setting, M, angular, app) {
  window.setting = setting;
  return angular.bootstrap(document.documentElement, ['app']);
});
