// Generated by IcedCoffeeScript 108.0.11

/*
 * File: routes
 * User: Dow
 * Date: 4/11/13
 * Desc:
 */
var cr, setting;

setting = require('../index-setting.json');

cr = require('../app/routers/frame/router');

module.exports = function() {
  var predictiveRouter;
  predictiveRouter = new cr.Router(setting, this);
  return predictiveRouter.start();
};
