// Generated by IcedCoffeeScript 1.8.0-c
var web;

web = require('clc.foundation.web');

module.exports = function() {
  var development;
  development = new web.Development(this);
  return development.initialize();
};
