// Generated by IcedCoffeeScript 108.0.11

/*
* File: home_controller
* User: Dow
* Date: 2/6/2015
* Desc:
 */
var controller;

controller = require('../../controllers-src/frame/home-controller');

module.exports = new controller.HomeController;
