// Generated by IcedCoffeeScript 108.0.11

/*
* File: guarder-module
* User: Dow
* Date: 2014/10/8
 */
if (typeof define !== 'function') { var define = require('amdefine')(module) };
define(['angular', 'clc.materialize'], function(angular) {
  return angular.module('clc.frame', ['clc.materialize']);
});
