// Generated by IcedCoffeeScript 108.0.11

/*
* File: iiot-header-directive
* User: David
* Date: 2018/11/17
* Desc:
 */
if (typeof define !== 'function') { var define = require('amdefine')(module) };
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['../base-directive', 'text!./style.css', 'text!./view.html', 'underscore', "moment"], function(base, css, view, _, moment) {
  var IiotHeaderDirective, exports;
  IiotHeaderDirective = (function(_super) {
    __extends(IiotHeaderDirective, _super);

    function IiotHeaderDirective($timeout, $window, $compile, $routeParams, commonService) {
      this.show = __bind(this.show, this);
      this.id = "iiot-header";
      IiotHeaderDirective.__super__.constructor.call(this, $timeout, $window, $compile, $routeParams, commonService);
    }

    IiotHeaderDirective.prototype.setScope = function() {};

    IiotHeaderDirective.prototype.setCSS = function() {
      return css;
    };

    IiotHeaderDirective.prototype.setTemplate = function() {
      return view;
    };

    IiotHeaderDirective.prototype.show = function(scope, element, attrs) {
      scope.setting = setting;
      return this.getStation(scope, "_elesys_manager_station", (function(_this) {
        return function() {
          return _this.getEquipment(scope, "_manager_equipment");
        };
      })(this));
    };

    IiotHeaderDirective.prototype.resize = function(scope) {};

    IiotHeaderDirective.prototype.dispose = function(scope) {};

    return IiotHeaderDirective;

  })(base.BaseDirective);
  return exports = {
    IiotHeaderDirective: IiotHeaderDirective
  };
});
