// Generated by IcedCoffeeScript 108.0.11

/*
* File: frame-service
* User: Pu
* Date: 2018/9/1
* Desc:
 */
if (typeof define !== 'function') { var define = require('amdefine')(module) };
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['clc.foundation.angular/services/rpc-service'], function(base) {
  var PredictiveService, exports;
  PredictiveService = (function(_super) {
    __extends(PredictiveService, _super);

    function PredictiveService($rootScope, httpService) {
      PredictiveService.__super__.constructor.call(this, $rootScope, httpService);
    }

    PredictiveService.prototype.echo = function(parameters, callback) {
      return this.rpc('echo', parameters, callback);
    };

    return PredictiveService;

  })(base.RpcService);
  return exports = {
    PredictiveService: PredictiveService
  };
});
